### ISSUE TITLE
don't know why http://localhost:6006/stories.json always 404

### ISSUE THREAD

**Issue by yolio2003** [bensmithett/tropical#32]
as title said when running `yarn storybook` 

node 16
windows 10
chrome

after open browser
there is a 404 error on network

and console error shows:
```
GET http://localhost:6006/stories.json 404 (Not Found)
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

[vite] connecting...
[vite] connected.

Uncaught SyntaxError: The requested module '/@fs/***/node_modules/slash/index.js?v=08316dd6' does not provide an export named 'default'

```

**Comment by Moshyfawn** [comment]
It might've been the ESM vs CJS issue, actually, like nodejs/node#32137. Maybe fixed with [the latest version](https://github.com/bensmithett/tropical/releases/tag/v10.0.0)?

**Comment by bensmithett** [comment]
@Moshyfawn could have been, cheers. I'll close for now, if anyone has the same issue feel free to reopen.
